name: Feedback & Suggestions
description: Share your feedback, suggestions, or general thoughts about Engage Time
title: "[FEEDBACK] "
labels: ["feedback"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for sharing your feedback! Your insights help us improve Engage Time for everyone.

  - type: checkboxes
    id: feedback-type
    attributes:
      label: Feedback Type
      description: What type of feedback are you providing?
      options:
        - label: General suggestion
        - label: User experience feedback
        - label: Performance feedback
        - label: Documentation feedback
        - label: Training methodology feedback
        - label: Accessibility feedback
        - label: Integration feedback
        - label: Pricing/Business feedback

  - type: input
    id: other-feedback-type
    attributes:
      label: Other Feedback Type
      description: If none of the above categories fit, please specify
      placeholder: Describe the type of feedback you're providing...

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Share your feedback, thoughts, or suggestions
      placeholder: Tell us what's on your mind...
    validations:
      required: true

  - type: textarea
    id: current-experience
    attributes:
      label: Current Experience
      description: Describe your current experience with Engage Time
      placeholder: How has your experience been so far?

  - type: dropdown
    id: your-role
    attributes:
      label: Your Role
      description: What is your primary role when using Engage Time?
      options:
        - Trainer/Facilitator
        - Learning Designer
        - Manager/Team Lead
        - Participant/Learner
        - IT Administrator
        - Decision Maker/Evaluator
        - Consultant
        - Other
    validations:
      required: true

  - type: checkboxes
    id: training-types
    attributes:
      label: Training Types
      description: What types of training do you conduct or participate in?
      options:
        - label: Corporate Training
        - label: Workshops
        - label: Educational Sessions
        - label: Conferences
        - label: Webinars
        - label: Team Meetings
        - label: Onboarding Sessions
        - label: Skills Development
        - label: Certification Programs
        - label: Sales Training

  - type: dropdown
    id: session-size
    attributes:
      label: Typical Session Size
      description: What size groups do you typically work with?
      options:
        - Small groups (5-10 people)
        - Medium groups (10-30 people)
        - Large groups (30-100 people)
        - Very large groups (100+ people)
        - Varies significantly

  - type: dropdown
    id: session-duration
    attributes:
      label: Typical Session Duration
      description: How long are your typical sessions?
      options:
        - 30 minutes or less
        - 30 minutes - 1 hour
        - 1-2 hours
        - 2-4 hours
        - Half day (4-6 hours)
        - Full day (6-8 hours)
        - Multi-day
        - Varies significantly

  - type: input
    id: industry
    attributes:
      label: Industry/Domain
      description: What industry or domain do you work in?
      placeholder: e.g., Technology, Healthcare, Education, Finance, Manufacturing, etc.

  - type: textarea
    id: working-well
    attributes:
      label: What's Working Well
      description: What aspects of Engage Time do you find most valuable?
      placeholder: Tell us what you love about Engage Time...

  - type: textarea
    id: areas-for-improvement
    attributes:
      label: Areas for Improvement
      description: What could be better? What challenges have you encountered?
      placeholder: What would you like to see improved?

  - type: textarea
    id: success-stories
    attributes:
      label: Success Stories
      description: Share any positive outcomes or success stories from using Engage Time
      placeholder: Tell us about a time when Engage Time really helped you...

  - type: textarea
    id: comparison
    attributes:
      label: Comparison & Inspiration
      description: Have you used similar tools? What features from other tools would you like to see?
      placeholder: How does Engage Time compare to other tools you've used?

  - type: textarea
    id: ideal-vision
    attributes:
      label: Ideal Vision
      description: If you could wave a magic wand, what would your ideal training tool look like?
      placeholder: Describe your dream training platform...

  - type: dropdown
    id: usage-frequency
    attributes:
      label: Usage Frequency
      description: How often do you use or plan to use Engage Time?
      options:
        - Daily
        - Weekly
        - Monthly
        - Occasionally
        - First time user/evaluating
        - Not currently using but interested

  - type: checkboxes
    id: contact-permission
    attributes:
      label: Contact Permission
      description: Follow-up options
      options:
        - label: You may contact me for clarification or follow-up questions
        - label: I'd like to be notified about updates related to my feedback
        - label: I'm interested in participating in user research or beta testing

  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: Any other thoughts, ideas, or context you'd like to share
      placeholder: Anything else you'd like us to know?